/**
 * Native Compiler — compiles hot skills into native code via pluggable
 * backends. Ships with a C++ (N-API-style node addon) backend that emits a
 * buildable source, and a no-op backend for tests/machines without a
 * toolchain.
 */

import * as fs from 'fs';
import * as path from 'path';
import { NativeArtifact, NativeBackend, CompiledSkill } from './SkillCompiler';
import { getLogger } from '../../core/Logger';

export interface CompilerConfig {
  /** C compiler used to build native addons. */
  cc?: string;
  /** Skip the actual build (emit source only). */
  emitOnly?: boolean;
}

export class CppBackend implements NativeBackend {
  readonly language = 'cpp';
  private cc: string;
  private emitOnly: boolean;

  constructor(config: CompilerConfig = {}) {
    this.cc = config.cc ?? 'g++';
    this.emitOnly = config.emitOnly ?? true;
  }

  async compile(skill: CompiledSkill, outDir: string): Promise<NativeArtifact> {
    const safe = skill.name.replace(/[^a-z0-9_]/gi, '_');
    const buildId = `${safe}_${skill.version.replace(/[^a-z0-9_.]/gi, '_')}`;
    const srcPath = path.join(outDir, `${buildId}.cpp`);
    fs.mkdirSync(outDir, { recursive: true });

    const nativeTools = skill.tools.filter(t => t.native);
    const methods = nativeTools
      .map(t => `  // tool: ${t.name}\n  //   ${t.description}\n  double _${t.name}(double in) { return in; }`)
      .join('\n');
    const source = `// Generated by Umbra Skill Compiler — ${skill.name} v${skill.version}
// Domain: ${skill.domain} | Hot: ${skill.hot} | Memory: ${skill.memorySize}B
#include <node_api.h>

${methods}

napi_value Entry(napi_env env, napi_callback_info info) {
  napi_value out;
  napi_create_double(env, 0, &out);
  return out;
}

NAPI_MODULE(NODE_GYP_MODULE_NAME, Init);
napi_value Init(napi_env env, napi_value exports) {
  napi_create_function(env, "invoke", NAPI_AUTO_LENGTH, Entry, nullptr, &exports);
  return exports;
}
`;
    fs.writeFileSync(srcPath, source, 'utf8');

    const artifact: NativeArtifact = {
      language: 'cpp',
      entry: 'invoke',
      sourcePath: srcPath,
      buildId,
    };

    if (!this.emitOnly) {
      try {
        this.build(srcPath, path.join(outDir, `${buildId}.node`));
      } catch (err) {
        getLogger().warn({ err, skill: skill.name }, 'Native build failed; source emitted only');
      }
    }
    return artifact;
  }

  private build(srcPath: string, outPath: string): void {
    const { execSync } = require('child_process') as typeof import('child_process');
    execSync(`"${this.cc}" -shared -fPIC -o "${outPath}" "${srcPath}" -lnode`, { stdio: 'pipe' });
  }
}

/** Backend that records compilation intent without producing binaries. */
export class NoopBackend implements NativeBackend {
  readonly language = 'noop';

  async compile(skill: CompiledSkill, outDir: string): Promise<NativeArtifact> {
    return {
      language: 'noop',
      entry: 'invoke',
      sourcePath: path.join(outDir, `${skill.name}.noop`),
      buildId: `${skill.name}-${skill.version}`,
    };
  }
}
